Product.create!([
  {title: "Jetty", description: "Lake Tahoe Jetty", image_url: "/images/Jetty-carousel.jpg", price: 20, size: nil, orientation: "landscape"},
  {title: "Chicago", description: "Chicago skyline", image_url: "/images/chicago-carousel.jpg", price: 30, size: nil, orientation: "landscape"},
  {title: "San Francisco", description: "View down a street in San Francisco", image_url: "/images/california-street.jpg", price: 30, size: nil, orientation: "portrait"},
  {title: "Rue Bourbon", description: "Classic New Orleans", image_url: "/images/rue-bourbon.jpg", price: 20, size: nil, orientation: "portrait"},
  {title: "Chicago", description: "Chicago skyline", image_url: "/images/chicago-carousel.jpg", price: 30, size: nil, orientation: "landscape"},
  {title: "San Francisco", description: "View down a street in San Francisco", image_url: "/images/california-street.jpg", price: 30, size: nil, orientation: "portrait"},
  {title: "Jetty", description: "Lake Tahoe Jetty", image_url: "/images/Jetty-carousel.jpg", price: 20, size: nil, orientation: "landscape"},
  {title: "Chicago", description: "Chicago skyline", image_url: "/images/chicago-carousel.jpg", price: 30, size: nil, orientation: "landscape"},
  {title: "Rue Bourbon", description: "Classic New Orleans", image_url: "/images/rue-bourbon.jpg", price: 20, size: nil, orientation: "portrait"},
  {title: "Jetty", description: "Lake Tahoe Jetty", image_url: "/images/Jetty-carousel.jpg", price: 20, size: nil, orientation: "landscape"},
  {title: "Jetty", description: "Lake Tahoe Jetty", image_url: "/images/Jetty-carousel.jpg", price: 20, size: nil, orientation: "landscape"},
  {title: "Chicago", description: "Chicago skyline", image_url: "/images/chicago-carousel.jpg", price: 30, size: nil, orientation: "landscape"},
  {title: "San Francisco", description: "View down a street in San Francisco", image_url: "/images/california-street.jpg", price: 30, size: nil, orientation: "portrait"},
  {title: "Rue Bourbon", description: "Classic New Orleans", image_url: "/images/rue-bourbon.jpg", price: 20, size: nil, orientation: "portrait"},
  {title: "Chicago", description: "Chicago skyline", image_url: "/images/chicago-carousel.jpg", price: 30, size: nil, orientation: "landscape"},
  {title: "San Francisco", description: "View down a street in San Francisco", image_url: "/images/california-street.jpg", price: 30, size: nil, orientation: "portrait"},
  {title: "Jetty", description: "Lake Tahoe Jetty", image_url: "/images/Jetty-carousel.jpg", price: 20, size: nil, orientation: "landscape"},
  {title: "Chicago", description: "Chicago skyline", image_url: "/images/chicago-carousel.jpg", price: 30, size: nil, orientation: "landscape"},
  {title: "Rue Bourbon", description: "Classic New Orleans", image_url: "/images/rue-bourbon.jpg", price: 20, size: nil, orientation: "portrait"},
  {title: "Jetty", description: "Lake Tahoe Jetty", image_url: "/images/Jetty-carousel.jpg", price: 20, size: nil, orientation: "landscape"}
])